defaults: &defaults
  wsaa_url: https://wsaahomo.afip.gov.ar/ws/services/LoginCms
  wsfe_url: https://wswhomo.afip.gov.ar/wsfev1/service.asmx
  wsaa_wsdl: /data/wsafip/wsaa.wsdl
  wsfe_wsdl: /data/wsafip/wsfev1.wsdl
  crt: /data/wsafip/sample.crt
  key: /data/wsafip/sample.key
  cuit: '30652143527'
  company: 'SAMPLE SA'

test:
  <<: *defaults

development:
  <<: *defaults


production:
  <<: *defaults
  wsaa_url: https://wsaa.afip.gov.ar/ws/services/LoginCms
  wsfe_url: https://servicios1.afip.gov.ar/wsfev1/service.asmx
  wsaa_wsdl: /data/wsafip/wsaa.wsdl
  wsfe_wsdl: /data/wsafip/wsfev1.wsdl
  crt: /data/wsafip/sample.crt
  key: /data/wsafip/sample.key
  cuit: '30652143527'
  company: 'SAMPLE SA'
