defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: marino

test:
  <<: *defaults
  database: marino_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
